# Site settings
title: "Tushar's Resume"
description: "Resume showcasing all my skills and experiences"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Tushar Chopra"
resume_title:                   "CSE Sophomore at FoT, UoD"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "tushar@ce.du.ac.in"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+919810282723"
resume_contact_address:         "Faculty of Technology, University of Delhi"

resume_header_contact_info:     "Faculty of Technology, University of Delhi • +919810282723 • tushar@ce.du.ac.in"
display_header_contact_info:    "false"

resume_header_intro: "<p>Computer Science and Engineering student with hands-on experience in cybersecurity, AI/ML, and web development. Seeking to leverage technical expertise and problem-solving skills in a professional setting. Open to growth opportunities in cybersecurity, AI, and digital forensics.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/TheTusharChopra"
  resume_twitter_url:           "http://twitter.com/tusharchopra_"
  # resume_dribbble_url:          "https://dribbble.com/"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/tusharchopra01"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://tushar.wiki"
  # resume_medium_url:            "https://medium.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
